"""Branch details as supplied by AABrick.

Generated from the branch worksheet. The catalogue lives in
the database and does not travel with a git pull, so what a
deploy needs to rebuild is committed here as code.

A blank whatsapp is deliberate: the column came back filled
by Excel's fill handle, which increments a phone number, so
any value that did not match its own phone was dropped
rather than published as somebody else's line.
"""

BRANCHES = [
    {
        "branch": 'Kabwe',
        "counter_or_depot": 'Counter',
        "street_address": 'ZEPH BUILDING, INDEPENDENCE WAY . KABWE.',
        "landmark": '',
        "town": 'Kabwe',
        "phone": '+260 97 008 3378',
        "whatsapp": '+260 97 008 3378',
        "email": 'sales@aabrick.com',
        "hours_weekday": '08:00 - 17:00',
        "hours_saturday": '08:00 - 14:00',
        "hours_sunday": 'Closed',
        "hours_note": '',
        "maps_url": '',
    },
    {
        "branch": 'Kapiri',
        "counter_or_depot": 'Counter',
        "street_address": 'Great North Road, opposite Pep Stores, next to Building Society Bank, Shop No. 5',
        "landmark": '',
        "town": 'Kapiri',
        "phone": '+260 76 456 7709',
        "whatsapp": '+260 76 456 7709',
        "email": 'sales@aabrick.com',
        "hours_weekday": '08:00 - 17:00',
        "hours_saturday": '08:00 - 14:00',
        "hours_sunday": 'Closed',
        "hours_note": '',
        "maps_url": '',
    },
    {
        "branch": 'Mkushi',
        "counter_or_depot": 'Counter',
        "street_address": 'Town center along president avenue road',
        "landmark": '',
        "town": 'Mkushi',
        "phone": '+260 77 100 0101',
        "whatsapp": '+260 77 100 0101',
        "email": 'sales@aabrick.com',
        "hours_weekday": '08:00 - 17:00',
        "hours_saturday": '08:00 - 14:00',
        "hours_sunday": 'Closed',
        "hours_note": '',
        "maps_url": '',
    },
    {
        "branch": 'Serenje',
        "counter_or_depot": 'Counter',
        "street_address": 'Along serenje radio station',
        "landmark": '',
        "town": 'Serenje',
        "phone": '+260 77 170 1055',
        "whatsapp": '+260 77 170 1055',
        "email": 'sales@aabrick.com',
        "hours_weekday": '08:00 - 17:00',
        "hours_saturday": '08:00 - 14:00',
        "hours_sunday": 'Closed',
        "hours_note": '',
        "maps_url": '',
    },
    {
        "branch": 'Chililabombwe',
        "counter_or_depot": 'Counter',
        "street_address": '4205 International Road',
        "landmark": '',
        "town": 'Chililabombwe',
        "phone": '+260 77 012 8380',
        "whatsapp": '+260 77 012 8380',
        "email": 'sales@aabrick.com',
        "hours_weekday": '08:00 - 17:00',
        "hours_saturday": '08:00 - 14:00',
        "hours_sunday": 'Closed',
        "hours_note": '',
        "maps_url": '',
    },
    {
        "branch": 'Chingola',
        "counter_or_depot": 'Counter',
        "street_address": '12th street nchanga north house number 65/67',
        "landmark": '',
        "town": 'Chingola',
        "phone": '+260 96 995 5755',
        "whatsapp": '+260 96 995 5755',
        "email": 'sales@aabrick.com',
        "hours_weekday": '08:00 - 17:00',
        "hours_saturday": '08:00 - 14:00',
        "hours_sunday": 'Closed',
        "hours_note": '',
        "maps_url": '',
    },
    {
        "branch": 'Kalulushi',
        "counter_or_depot": 'Counter',
        "street_address": 'A55 President Ave Patterson round about',
        "landmark": '',
        "town": 'Kalulushi',
        "phone": '+260 97 231 7565',
        "whatsapp": '+260 97 231 7565',
        "email": 'sales@aabrick.com',
        "hours_weekday": '08:00 - 17:00',
        "hours_saturday": '08:00 - 14:00',
        "hours_sunday": 'Closed',
        "hours_note": '',
        "maps_url": '',
    },
    {
        "branch": 'Kasumbalesa',
        "counter_or_depot": 'Counter',
        "street_address": 'SUB S/D K206 KASUMBALESA / Next to Zambeef',
        "landmark": '',
        "town": 'Kasumbalesa',
        "phone": '+260 77 489 6536',
        "whatsapp": '+260 77 489 6536',
        "email": 'sales@aabrick.com',
        "hours_weekday": '08:00 - 17:00',
        "hours_saturday": '08:00 - 14:00',
        "hours_sunday": 'Closed',
        "hours_note": '',
        "maps_url": '',
    },
    {
        "branch": 'Kitwe Main',
        "counter_or_depot": 'Counter',
        "street_address": 'Light Industry Area, Plot 840, off,/7344 Nyerere Road Pende Electrical & Hardware Light Industrial Area Kitwe',
        "landmark": '',
        "town": 'Kitwe',
        "phone": '+260 96 927 9307',
        "whatsapp": '+260 96 927 9307',
        "email": 'sales@aabrick.com',
        "hours_weekday": '08:00 - 17:00',
        "hours_saturday": '08:00 - 14:00',
        "hours_sunday": 'Closed',
        "hours_note": '',
        "maps_url": '',
    },
    {
        "branch": 'Luanshya',
        "counter_or_depot": 'Counter',
        "street_address": 'Shop 92 industrial area ,second class',
        "landmark": '',
        "town": 'Luanshya',
        "phone": '+260 76 074 9747',
        "whatsapp": '+260 76 074 9747',
        "email": 'sales@aabrick.com',
        "hours_weekday": '08:00 - 17:00',
        "hours_saturday": '08:00 - 14:00',
        "hours_sunday": 'Closed',
        "hours_note": '',
        "maps_url": '',
    },
    {
        "branch": 'Mufulira',
        "counter_or_depot": 'Counter',
        "street_address": '227A chisokone street Mufulira',
        "landmark": '',
        "town": 'Mufulira',
        "phone": '+260 97 208 5334',
        "whatsapp": '+260 97 208 5334',
        "email": 'sales@aabrick.com',
        "hours_weekday": '08:00 - 17:00',
        "hours_saturday": '08:00 - 14:00',
        "hours_sunday": 'Closed',
        "hours_note": '',
        "maps_url": '',
    },
    {
        "branch": 'Ndeke',
        "counter_or_depot": 'Counter',
        "street_address": '26027 21th avenue Nkana east- Mwaiseni next to Vagabond pub',
        "landmark": '',
        "town": 'Kitwe',
        "phone": '+260 77 737 3480',
        "whatsapp": '+260 77 737 3480',
        "email": 'sales@aabrick.com',
        "hours_weekday": '08:00 - 17:00',
        "hours_saturday": '08:00 - 14:00',
        "hours_sunday": 'Closed',
        "hours_note": '',
        "maps_url": '',
    },
    {
        "branch": 'Ndola 2',
        "counter_or_depot": 'Counter',
        "street_address": 'Northrise, Shinde Street, Shop #2',
        "landmark": '',
        "town": 'Ndola',
        "phone": '+260 96 649 8553',
        "whatsapp": '+260 96 649 8553',
        "email": 'sales@aabrick.com',
        "hours_weekday": '08:00 - 17:00',
        "hours_saturday": '08:00 - 14:00',
        "hours_sunday": 'Closed',
        "hours_note": '',
        "maps_url": '',
    },
    {
        "branch": 'Ndola Main',
        "counter_or_depot": 'Counter',
        "street_address": '19C president avenue opposite fire prevention',
        "landmark": '',
        "town": 'Ndola',
        "phone": '+260 77 439 0258',
        "whatsapp": '+260 77 439 0258',
        "email": 'sales@aabrick.com',
        "hours_weekday": '08:00 - 17:00',
        "hours_saturday": '08:00 - 14:00',
        "hours_sunday": 'Closed',
        "hours_note": '',
        "maps_url": '',
    },
    {
        "branch": 'Kawambwa',
        "counter_or_depot": 'Counter',
        "street_address": 'Along mushota road next to Ndundumbo wa ndundumbo shop',
        "landmark": '',
        "town": 'Kawambwa',
        "phone": '+260 97 312 1715',
        "whatsapp": '+260 97 312 1715',
        "email": 'sales@aabrick.com',
        "hours_weekday": '08:00 - 17:00',
        "hours_saturday": '08:00 - 14:00',
        "hours_sunday": 'Closed',
        "hours_note": '',
        "maps_url": '',
    },
    {
        "branch": 'Mansa',
        "counter_or_depot": 'Counter',
        "street_address": 'along Chimpampwe road opposite mansa Debs next to Mabro Auto Shop',
        "landmark": '',
        "town": 'Mansa',
        "phone": '+260 97 239 7607',
        "whatsapp": '',
        "email": 'sales@aabrick.com',
        "hours_weekday": '08:00 - 17:00',
        "hours_saturday": '08:00 - 14:00',
        "hours_sunday": 'Closed',
        "hours_note": '',
        "maps_url": '',
    },
    {
        "branch": 'Samfya',
        "counter_or_depot": 'Counter',
        "street_address": '',
        "landmark": '',
        "town": 'Samfya',
        "phone": '+260 960 787 777',
        "whatsapp": '',
        "email": 'sales@aabrick.com',
        "hours_weekday": '08:00 - 17:00',
        "hours_saturday": '08:00 - 14:00',
        "hours_sunday": 'Closed',
        "hours_note": '',
        "maps_url": '',
    },
    {
        "branch": 'Chinsali',
        "counter_or_depot": 'Counter',
        "street_address": 'Green Road',
        "landmark": '',
        "town": 'Chinsali',
        "phone": '+260 77 373 7378',
        "whatsapp": '',
        "email": 'sales@aabrick.com',
        "hours_weekday": '08:00 - 17:00',
        "hours_saturday": '08:00 - 14:00',
        "hours_sunday": 'Closed',
        "hours_note": '',
        "maps_url": '',
    },
    {
        "branch": 'Mpika',
        "counter_or_depot": 'Counter',
        "street_address": 'Green farmer road',
        "landmark": '',
        "town": 'Mpika',
        "phone": '+260 97 460 6915',
        "whatsapp": '+260 97 460 6915',
        "email": 'sales@aabrick.com',
        "hours_weekday": '08:00 - 17:00',
        "hours_saturday": '08:00 - 14:00',
        "hours_sunday": 'Closed',
        "hours_note": '',
        "maps_url": '',
    },
    {
        "branch": 'Manyama',
        "counter_or_depot": 'Counter',
        "street_address": 'along mwinilunga road side manyama oposite St Anne',
        "landmark": '',
        "town": 'Manyama',
        "phone": '+260 97 833 8720',
        "whatsapp": '+260 97 833 8720',
        "email": 'sales@aabrick.com',
        "hours_weekday": '08:00 - 17:00',
        "hours_saturday": '08:00 - 14:00',
        "hours_sunday": 'Closed',
        "hours_note": '',
        "maps_url": '',
    },
    {
        "branch": 'Solwezi',
        "counter_or_depot": 'Counter',
        "street_address": 'Off Independence Road, Diankala Street, next to Zambia Breweries',
        "landmark": '',
        "town": 'Solwezi',
        "phone": '+260 96 192 8311',
        "whatsapp": '+260 96 192 8311',
        "email": 'sales@aabrick.com',
        "hours_weekday": '08:00 - 17:00',
        "hours_saturday": '08:00 - 14:00',
        "hours_sunday": 'Closed',
        "hours_note": '',
        "maps_url": '',
    },
    {
        "branch": 'Kasama',
        "counter_or_depot": 'Counter',
        "street_address": 'Along luwingu road, former OPJT',
        "landmark": '',
        "town": 'Kasama',
        "phone": '+260 96 031 9999',
        "whatsapp": '+260 96 031 9999',
        "email": 'sales@aabrick.com',
        "hours_weekday": '08:00 - 17:00',
        "hours_saturday": '08:00 - 14:00',
        "hours_sunday": 'Closed',
        "hours_note": '',
        "maps_url": '',
    },
    {
        "branch": 'Luwingu',
        "counter_or_depot": 'Counter',
        "street_address": 'Luwingu branch address 310 corner stone barma',
        "landmark": '',
        "town": 'Luwingu',
        "phone": '+260 97 247 8013',
        "whatsapp": '+260 97 247 8013',
        "email": 'sales@aabrick.com',
        "hours_weekday": '08:00 - 17:00',
        "hours_saturday": '08:00 - 14:00',
        "hours_sunday": 'Closed',
        "hours_note": '',
        "maps_url": '',
    },
    {
        "branch": 'Chipata',
        "counter_or_depot": 'Counter',
        "street_address": 'Along Great East Road, next to Old Bakery',
        "landmark": '',
        "town": 'Chipata',
        "phone": '+260 77 237 7705',
        "whatsapp": '+260 77 237 7705',
        "email": 'sales@aabrick.com',
        "hours_weekday": '08:00 - 17:00',
        "hours_saturday": '08:00 - 14:00',
        "hours_sunday": 'Closed',
        "hours_note": '',
        "maps_url": '',
    },
    {
        "branch": 'Katete',
        "counter_or_depot": 'Counter',
        "street_address": 'Along great East Road opposite Dumela',
        "landmark": '',
        "town": 'Katete',
        "phone": '+260 77 259 9159',
        "whatsapp": '+260 77 259 9159',
        "email": 'sales@aabrick.com',
        "hours_weekday": '08:00 - 17:00',
        "hours_saturday": '08:00 - 14:00',
        "hours_sunday": 'Closed',
        "hours_note": '',
        "maps_url": '',
    },
    {
        "branch": 'Lundazi',
        "counter_or_depot": 'Counter',
        "street_address": 'Aliboos Mall',
        "landmark": '',
        "town": 'Lundazi',
        "phone": '+260 97 924 8467',
        "whatsapp": '+260 97 924 8467',
        "email": 'sales@aabrick.com',
        "hours_weekday": '08:00 - 17:00',
        "hours_saturday": '08:00 - 14:00',
        "hours_sunday": 'Closed',
        "hours_note": '',
        "maps_url": '',
    },
    {
        "branch": 'Nyimba',
        "counter_or_depot": 'Counter',
        "street_address": 'old Zonse, along great East road',
        "landmark": '',
        "town": 'Nyimba',
        "phone": '+260 97 873 6517',
        "whatsapp": '+260 97 873 6517',
        "email": 'sales@aabrick.com',
        "hours_weekday": '08:00 - 17:00',
        "hours_saturday": '08:00 - 14:00',
        "hours_sunday": 'Closed',
        "hours_note": '',
        "maps_url": '',
    },
    {
        "branch": 'Petauke',
        "counter_or_depot": 'Counter',
        "street_address": 'Petauke main Boma road Plot no81883, R.C.Z Road',
        "landmark": '',
        "town": 'Petauke',
        "phone": '+260 97 676 2254',
        "whatsapp": '',
        "email": 'sales@aabrick.com',
        "hours_weekday": '08:00 - 17:00',
        "hours_saturday": '08:00 - 14:00',
        "hours_sunday": 'Closed',
        "hours_note": '',
        "maps_url": '',
    },
    {
        "branch": 'Sinda',
        "counter_or_depot": 'Counter',
        "street_address": 'along the great east road, Sinda Town, Opposite New Market',
        "landmark": '',
        "town": 'Sinda',
        "phone": '+260 77 614 1055',
        "whatsapp": '+260 77 614 1055',
        "email": 'sales@aabrick.com',
        "hours_weekday": '08:00 - 17:00',
        "hours_saturday": '08:00 - 14:00',
        "hours_sunday": 'Closed',
        "hours_note": '',
        "maps_url": '',
    },
    {
        "branch": '9 Miles',
        "counter_or_depot": 'Counter',
        "street_address": '',
        "landmark": '',
        "town": 'Lusaka',
        "phone": '+260 960 787 777',
        "whatsapp": '',
        "email": 'sales@aabrick.com',
        "hours_weekday": '08:00 - 17:00',
        "hours_saturday": '08:00 - 14:00',
        "hours_sunday": 'Closed',
        "hours_note": '',
        "maps_url": '',
    },
    {
        "branch": 'Chalala',
        "counter_or_depot": 'Counter',
        "street_address": 'Manna mall area chalala along kasama road',
        "landmark": '',
        "town": 'Lusaka',
        "phone": '+260 97 587 9078',
        "whatsapp": '+260 97 587 9078',
        "email": 'sales@aabrick.com',
        "hours_weekday": '08:00 - 17:00',
        "hours_saturday": '08:00 - 14:00',
        "hours_sunday": 'Closed',
        "hours_note": '',
        "maps_url": '',
    },
    {
        "branch": 'Garden House',
        "counter_or_depot": 'Counter',
        "street_address": 'GARDEN HOUSE Shop No 6',
        "landmark": '',
        "town": 'Lusaka',
        "phone": '+260 97 410 4024',
        "whatsapp": '+260 97 410 4024',
        "email": 'sales@aabrick.com',
        "hours_weekday": '08:00 - 17:00',
        "hours_saturday": '08:00 - 14:00',
        "hours_sunday": 'Closed',
        "hours_note": '',
        "maps_url": '',
    },
    {
        "branch": 'Kafue',
        "counter_or_depot": 'Counter',
        "street_address": 'North great road Plot No.1286 / Next to Young phiroz shop',
        "landmark": '',
        "town": 'Kafue',
        "phone": '+260 97 944 6565',
        "whatsapp": '+260 97 944 6565',
        "email": 'sales@aabrick.com',
        "hours_weekday": '08:00 - 17:00',
        "hours_saturday": '08:00 - 14:00',
        "hours_sunday": 'Closed',
        "hours_note": '',
        "maps_url": '',
    },
    {
        "branch": 'Lusaka Great North',
        "counter_or_depot": 'Counter',
        "street_address": '',
        "landmark": '',
        "town": 'Lusaka',
        "phone": '+260 96 078 7777',
        "whatsapp": '+260 96 078 7777',
        "email": 'sales@aabrick.com',
        "hours_weekday": '08:00 - 17:00',
        "hours_saturday": '08:00 - 14:00',
        "hours_sunday": 'Closed',
        "hours_note": '',
        "maps_url": '',
    },
    {
        "branch": 'Meanwood',
        "counter_or_depot": 'Counter',
        "street_address": '',
        "landmark": '',
        "town": 'Lusaka',
        "phone": '+260 96 078 7777',
        "whatsapp": '+260 96 078 7777',
        "email": 'sales@aabrick.com',
        "hours_weekday": '08:00 - 17:00',
        "hours_saturday": '08:00 - 14:00',
        "hours_sunday": 'Closed',
        "hours_note": '',
        "maps_url": '',
    },
    {
        "branch": 'Mungwi',
        "counter_or_depot": 'Counter',
        "street_address": 'Mumbwa S.B.D, off mumbwa Road. Former Farmers Union Building.',
        "landmark": '',
        "town": 'Lusaka',
        "phone": '+260 96 602 0577',
        "whatsapp": '',
        "email": 'sales@aabrick.com',
        "hours_weekday": '08:00 - 17:00',
        "hours_saturday": '08:00 - 14:00',
        "hours_sunday": 'Closed',
        "hours_note": '',
        "maps_url": '',
    },
    {
        "branch": 'Silverest',
        "counter_or_depot": 'Counter',
        "street_address": '',
        "landmark": '',
        "town": 'Lusaka',
        "phone": '+260 96 078 7777',
        "whatsapp": '',
        "email": 'sales@aabrick.com',
        "hours_weekday": '08:00 - 17:00',
        "hours_saturday": '08:00 - 14:00',
        "hours_sunday": 'Closed',
        "hours_note": '',
        "maps_url": '',
    },
    {
        "branch": 'SOS',
        "counter_or_depot": 'Counter',
        "street_address": 'Sos Great North Road ship No5',
        "landmark": '',
        "town": 'Lusaka',
        "phone": '+260 97 457 4575',
        "whatsapp": '+260 97 457 4575',
        "email": 'sales@aabrick.com',
        "hours_weekday": '08:00 - 17:00',
        "hours_saturday": '08:00 - 14:00',
        "hours_sunday": 'Closed',
        "hours_note": '',
        "maps_url": '',
    },
    {
        "branch": 'Choma',
        "counter_or_depot": 'Counter',
        "street_address": 'Plot No.5814 Livingstone Road / Easy Home Mall',
        "landmark": '',
        "town": 'Choma',
        "phone": '+260 77 132 9777',
        "whatsapp": '+260 77 132 9777',
        "email": 'sales@aabrick.com',
        "hours_weekday": '08:00 - 17:00',
        "hours_saturday": '08:00 - 14:00',
        "hours_sunday": 'Closed',
        "hours_note": '',
        "maps_url": '',
    },
    {
        "branch": 'Kalomo',
        "counter_or_depot": 'Counter',
        "street_address": 'shop No 710616/2 Along Livingston road',
        "landmark": '',
        "town": 'Kalomo',
        "phone": '+260 77 159 0866',
        "whatsapp": '+260 77 159 0866',
        "email": 'sales@aabrick.com',
        "hours_weekday": '08:00 - 17:00',
        "hours_saturday": '08:00 - 14:00',
        "hours_sunday": 'Closed',
        "hours_note": '',
        "maps_url": '',
    },
    {
        "branch": 'Livingstone',
        "counter_or_depot": 'Counter',
        "street_address": '904 Mosi-o-Tunya Road, between Zanaco and Auto World, opposite Pep Stores',
        "landmark": '',
        "town": 'Livingstone',
        "phone": '+260 97 758 1285',
        "whatsapp": '',
        "email": 'sales@aabrick.com',
        "hours_weekday": '08:00 - 17:00',
        "hours_saturday": '08:00 - 14:00',
        "hours_sunday": 'Closed',
        "hours_note": '',
        "maps_url": '',
    },
    {
        "branch": 'Mazabuka',
        "counter_or_depot": 'Counter',
        "street_address": 'Main Street, next to Hungry Lion.',
        "landmark": '',
        "town": 'Mazabuka',
        "phone": '+260 96 717 9100',
        "whatsapp": '',
        "email": 'sales@aabrick.com',
        "hours_weekday": '08:00 - 17:00',
        "hours_saturday": '08:00 - 14:00',
        "hours_sunday": 'Closed',
        "hours_note": '',
        "maps_url": '',
    },
    {
        "branch": 'Monze',
        "counter_or_depot": 'Counter',
        "street_address": 'Plot No #3331 along Livingstone road, Old Barclays bank behind (Indo Zambia Bank)',
        "landmark": '',
        "town": 'Monze',
        "phone": '+260 96 346 3816',
        "whatsapp": '',
        "email": 'sales@aabrick.com',
        "hours_weekday": '08:00 - 17:00',
        "hours_saturday": '08:00 - 14:00',
        "hours_sunday": 'Closed',
        "hours_note": '',
        "maps_url": '',
    },
    {
        "branch": 'Kaoma',
        "counter_or_depot": 'Counter',
        "street_address": 'Along freedom way, next to Dstv.',
        "landmark": '',
        "town": 'Kaoma',
        "phone": '+260 77 673 5468',
        "whatsapp": '+260 77 673 5468',
        "email": 'sales@aabrick.com',
        "hours_weekday": '08:00 - 17:00',
        "hours_saturday": '08:00 - 14:00',
        "hours_sunday": 'Closed',
        "hours_note": '',
        "maps_url": '',
    },
    {
        "branch": 'Mongu',
        "counter_or_depot": 'Counter',
        "street_address": 'No.165 Zambezi Area along Independence Avenue, behind Indo Zambia bank',
        "landmark": '',
        "town": 'Mongu',
        "phone": '+260 76 755 7017',
        "whatsapp": '+260 76 755 7017',
        "email": 'sales@aabrick.com',
        "hours_weekday": '08:00 - 17:00',
        "hours_saturday": '08:00 - 14:00',
        "hours_sunday": 'Closed',
        "hours_note": '',
        "maps_url": '',
    },
    {
        "branch": 'Senanga',
        "counter_or_depot": 'Counter',
        "street_address": 'Plot no 985 Along Senanga Mongu Road.',
        "landmark": '',
        "town": 'Senanga',
        "phone": '+260 96 962 6963',
        "whatsapp": '+260 96 962 6963',
        "email": 'sales@aabrick.com',
        "hours_weekday": '08:00 - 17:00',
        "hours_saturday": '08:00 - 14:00',
        "hours_sunday": 'Closed',
        "hours_note": '',
        "maps_url": '',
    },
]
